let data = [
    {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Revised Request",
        time: "2h 13m left", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Editorial Review",
        time: "Waiting", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Deadline Missed",
        time: "N/A", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
        {
        title: "How to build an E-commerece Website",
        subtitle: "e-book  |  Travels and Tourism  |  400 words",
        amount: 400,
        status: "Completed",
        time: "4.5", 
    },
]

module.exports = data